# Generated by Django 5.1 on 2024-09-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account_view',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('acc', models.CharField(max_length=250)),
                ('ifsc', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='salary_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc', models.CharField(max_length=250)),
                ('branch', models.CharField(max_length=120)),
            ],
        ),
    ]
