# Generated by Django 5.1 on 2024-09-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInsuranceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('medical_history', models.TextField()),
                ('health_doc', models.FileField(upload_to='health_docs/')),
            ],
        ),
        migrations.CreateModel(
            name='LifeInsuranceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('policy_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('identity_doc', models.FileField(upload_to='life_insurance_documents/')),
            ],
        ),
    ]
