# Generated by Django 5.1 on 2024-09-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInsuranceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_make', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=20)),
                ('insurance_doc', models.FileField(upload_to='insurance_documents/')),
            ],
        ),
    ]
