# Generated by Django 5.1 on 2024-09-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accountpayTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_Name', models.CharField(max_length=255)),
                ('account_Number', models.CharField(max_length=255)),
                ('ifsc', models.CharField(max_length=16)),
                ('amount', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='create_documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='')),
                ('aadhar_card', models.FileField(upload_to='')),
                ('pan_card', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='create_nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile_no', models.IntegerField()),
                ('relationship', models.CharField(max_length=50)),
                ('date', models.DateField(max_length=10)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='create_reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile_no', models.IntegerField()),
                ('address1', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Createaccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('mobile_no', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('utype', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=100)),
                ('balance', models.CharField(blank=True, default=0.0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Createaccountuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('mobile_no', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('utype', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='payeedetailsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_Name', models.CharField(max_length=255)),
                ('account_Number', models.CharField(max_length=255)),
                ('ifsc', models.CharField(max_length=16)),
                ('bankname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetailsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardtype', models.CharField(max_length=255)),
                ('cardholdername', models.CharField(max_length=255)),
                ('cardnumber', models.CharField(max_length=16)),
                ('expirydate', models.CharField(max_length=255)),
                ('cvv', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='user_register',
            fields=[
                ('user_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=120)),
            ],
        ),
    ]
