# Generated by Django 5.1 on 2024-09-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='card_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=20)),
                ('customer_id', models.CharField(max_length=20)),
                ('card_type', models.CharField(max_length=10)),
                ('card_number', models.CharField(max_length=16)),
                ('expiry_date', models.CharField(max_length=20)),
                ('cvv', models.CharField(max_length=4)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
