from django.urls import path
from . import views
urlpatterns = [
    path("",views.landingpage,name='landingpage'),
    path("createaccount/",views.createaccount,name='createaccount'),
    path("document/",views.documentupload,name='document'),
    path("nominee/",views.nominee,name='nominee'),
    path("references/",views.references,name='references'),
    path("user/",views.user,name='user'),
    path("loginform/",views.loginform,name='loginform'),
    path("signupform/",views.signupform,name='signupform'),
    path("customerdash/",views.customerdash,name='customerdash'),
    path("payment/",views.payment,name='payment'),
    path("paymentconfirm/",views.paymentconfirm,name='paymentconfirm'),
    path("createaccountuser/",views.createaccountuser,name='createaccountuser'),

    path("login_check", views.login_check.as_view(),name="login_check"),
    path("create_user", views.create_user.as_view(),name="create_user"),
    path("view_user", views.view_user.as_view(),name="view_user"),
    path("create_account", views.create_account.as_view(),name="create_account"),
    path("view_account", views.view_account.as_view(),name="view_account"),
    path("update_account_details", views.update_account_details.as_view(),name="update_account_details"),
    path("create_nominee", views.create_nominee_details.as_view(),name="create_nominee"),
    path("view_nominee", views.view_nominee.as_view(),name="view_nominee"),
    path("create_reference", views.CreateReference.as_view(),name="create_reference"),
    path("view_reference", views.view_reference.as_view(),name="view_reference"),
    path("create_documents", views.create_user_documents.as_view(),name="create_documents"),
    path("view_documents", views.view_documents.as_view(),name="view_documents"),
    path("user_login", views.user_login_view.as_view(),name="user_login"),
    path("view_login", views.view_login.as_view(),name="view_login"),
    path("deleteuser", views.deleteuser.as_view(),name="deleteuser"),
    path("removeuser", views.removeuser.as_view(),name="removeuser"),
    path("deleteaccount", views.deleteaccount.as_view(),name="deleteaccount"),
    path("deletedocuments", views.deletedocuments.as_view(),name="deletedocuments"),
    path("deletenominee", views.deletenominee.as_view(),name="deletenominee"),
    path("deletereference", views.deletereference1.as_view(),name="deletereference"),
    # path("payment_details", views.payment_details.as_view(),name="payment_details"),
    path("payment_detailsview", views.payment_detailsview.as_view(),name="payment_detailsview"),
    # path("view_accountadmin", views.view_accountadmin.as_view(),name="view_accountadmin"),
    path("logincheck", views.logincheck.as_view(), name='logincheck'),
    path("UserProfileView", views.UserProfileView.as_view(), name='UserProfileView'),
    path("accountpaydetails", views.accountpaydetails.as_view(), name='accountpaydetails'),
    path("accountpayview", views.accountpayview.as_view(), name='accountpayview'),
    path("UserPaymentView", views.UserPaymentView.as_view(), name='UserPaymentView'),
    path("payeedetails", views.payeedetails.as_view(), name='payeedetails'),
    path("payeedetailsview", views.payeedetailsview.as_view(), name='payeedetailsview'),
    path("payeetableview", views.payeetableview.as_view(), name='payeetableview'),
    path("payeecheck", views.payeecheck.as_view(), name='payeecheck'),
    path("create_account_user",views.create_account_user.as_view(),name='create_account_user'),
    path("view_account_user",views.view_account_user.as_view(),name='view_account_user'),
    path("UserDashboardView",views.UserDashboardView.as_view(),name='UserDashboardView'),
    path("AdminDashboardView",views.AdminDashboardView.as_view(),name='AdminDashboardView'),
    #path("customeroperations", views.customeroperations.as_view(), name='customeroperations'),

]